trigger: none

variables:
  resourceGroup: "vention-azure-CICD"
  clusterName: "vention-aks-cluster"
  subscription: "MyAzureStudentSubscription"

pool: "self-hosted-pool"

stages:
  - stage: DeployAKS
    jobs:
      - job:
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(subscription)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Check if cluster exists
                if ! az aks show --name $(clusterName) --resource-group $(resourceGroup) &>/dev/null; then
                  az aks create \
                    --resource-group $(resourceGroup) \
                    --name $(clusterName) \
                    --node-count 1 \
                    --generate-ssh-keys
                fi
          - template: get-cluster-credentials-task.yml

  - stage: DeployIngress
    dependsOn: DeployAKS
    jobs:
      - job:
        steps:
          - template: add-tool-installer-task.yml

          - script: |
              helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
              helm repo update
            displayName: Add Ingress NGINX Repo

          - task: HelmDeploy@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceConnection: "aks"
              command: "upgrade"
              chartName: "ingress-nginx/ingress-nginx"
              releaseName: "aks-ingress-nginx"
              install: true
              arguments: "--create-namespace --namespace ingress-basic"

  - stage: DeployApps
    dependsOn: DeployIngress
    jobs:
      - job:
        steps:
          - template: add-tool-installer-task.yml

          - script: |
              helm repo add bitnami https://charts.bitnami.com/bitnami
              helm repo add examples https://helm.github.io/examples
              helm repo update
            displayName: Add bitnami Repo

          - task: HelmDeploy@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceConnection: "aks"
              command: "upgrade"
              chartName: "examples/hello-world"
              releaseName: "app1"
              install: true
              arguments: "--set service.name=app1"

          - task: HelmDeploy@1
            inputs:
              connectionType: "Kubernetes Service Connection"
              kubernetesServiceConnection: "aks"
              command: "upgrade"
              chartName: "bitnami/wordpress"
              releaseName: "app2"
              install: true
              arguments: "--set service.name=app2-wordpress"

  - stage: ConfigureIngress
    dependsOn: DeployApps
    jobs:
      - job:
        steps:
          - template: add-tool-installer-task.yml

          - task: Kubernetes@1
            inputs:
              command: "apply"
              arguments: "-f kubernetes/ingress.yml"
